### ISSUE TITLE
Баг, вылет программы.

### ISSUE THREAD

**Issue by Pavelboop** [smailuly/Ulya_Oksana_Timeplanner#4]
У меня вылетает исключение после такой последовательности действий:1 запустил программу. 2 нажал кнопку настройки. там уже было введено save1.bin. 3 нажал применить появились записи в столбиках. 4 нажал на запись открылось окно редактирования. 5 закрыл это окно на крестик ничего не меняя. 6 нажал настройки. 7. нажал применить 8. вылетело исключение

**Comment by smailuly** [comment]
Проблема не обнаружена. Пожалуйста,пришлите скриншот ошибки и более точную информацию
